name: Deploy Mogenius Operator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Setup Kubernetes with kind
        uses: helm/kind-action@v1

      - name: Verify Kubernetes Context
        run: kubectl config current-context

      - name: Install Mogenius Operator
        run: |
          helm repo add mogenius https://helm.mogenius.com/public
          helm repo update mogenius
          helm upgrade --install mogenius-operator mogenius/mogenius-k8s-manager \
            -n mogenius --create-namespace --wait \
            --set global.cluster_name="Ilham" \
            --set global.api_key="mo_d14d5887-7ced-45b7-a8eb-67c7fa3cd10f_8otwuda54ahskzmi0kqg"

      - name: Wait for Operator Connection
        run: |
          echo "Waiting for operator connection..."
          sleep 30
          echo "Is this taking longer than expected?"
          echo "If you’re facing issues connecting the mogenius operator, check out troubleshooting options."
